### ISSUE TITLE
isPalindrome(a) Does Not Use Its Parameter

### ISSUE THREAD

**Issue by WiiWake3101** [omprakashbabu/Python_programs#1]
In the function `isPalindrome(a)`, the parameter `a` is not used. Instead, the function uses the global variables `str` and `str_rev`. This could lead to unexpected behavior if the global variables are changed elsewhere in the code.

Here's the current implementation of the function:

```python
def isPalindrome(a):
    if str == str_rev:
        print("The given string is Palindrome")
    else:
        print("The given string is not a Palindrome")
```

A possible solution would be to remove the parameter `a` and directly use the global variables in the function. Alternatively, you could pass `str` and `str_rev` as parameters to the function.

I would appreciate it if someone could look into this issue. Thank you!

**Comment by HariAr2** [comment]
```python
def isPalindrome(a):
    if a == a[::-1]:
        print("The given string is Palindrome")
    else:
        print("The given string is not a Palindrome")

``` 
use this code which is the corrected version of the code you have done

**Comment by HariAr2** [comment]
@WiiWake3101 thanks for your contribution I merged your code 
## THANK YOU
