### ISSUE TITLE
isPalindrome(a) Function to Handle Uppercase Input

### ISSUE THREAD

**Issue by WiiWake3101** [omprakashbabu/Python_programs#2]
The current implementation of the `isPalindrome(a)` function does not handle uppercase input correctly. It compares the input string with its reverse without converting them to a common case, which can lead to incorrect results if the input string is in uppercase.

Here's the current implementation of the function:

```python
def isPalindrome(a):
    if str == str_rev:
        print("The given string is Palindrome")
    else:
        print("The given string is not Palindrome")
```

A possible solution would be to convert the input string to lowercase before comparing it with its reverse. This would ensure that the function works correctly even if the input string is in uppercase. The function should also print the original string in its output, so the case of the input string is preserved in the output.

I would appreciate it if someone could look into this issue. Thank you!

**Comment by HariAr2** [comment]
Thanks for The issue @WiiWake3101  I will change it as per your request
